Sb
moj-analytical-services/hudi-vs-iceberg pull request #18
Opened 2023-05-25 17:49 UTC by sivabathina2

2023-05-31 17:23 UTC, SoumayaMauthoorMOJ commented
nice work so far @sivabathina2 ! Is this ready to merge in or did you want to make further changes?

2023-06-30 14:44 UTC, mamonu approved these changes

2023-07-03 08:29 UTC, SoumayaMauthoorMOJ commented
@sivabathina2 can please move the file to hudi_vs_iceberg/data_engineering/glue_jobs and rename to pyspark functions?

2023-07-03 08:30 UTC, SoumayaMauthoorMOJ requested changes
@sivabathina2 can please move the file to hudi_vs_iceberg/data_engineering/glue_jobs and rename to pyspark functions?

2023-07-03 14:53 UTC, mamonu approved these changes

2023-07-03 15:25 UTC, SoumayaMauthoorMOJ approved these changes

2023-07-03 15:25 UTC, merged